### ISSUE TITLE
Gui segfaults in 'Puzzle' Tab

### ISSUE THREAD

**Issue by raoulb** [burr-tools/burr-tools#16]
The burrGui segfaults in the 'Puzzle' tab. To reproduce create a simple shape (one cube is sufficient) in the 'Entities' tab, then go to the 'Puzzle' tab and click/drag on the 3D panel in the right half of the window.

**Comment by raoulb** [comment]
Here is a backtrace obtained on a Debian sid installation:

```
#0  0x00007fffee8efb2c in ?? () from /lib/x86_64-linux-gnu/libLLVM-14.so.1
#1  0x00007fffee932b83 in LLVMBuildBitCast () from /lib/x86_64-linux-gnu/libLLVM-14.so.1
#2  0x00007ffff4a8b028 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#3  0x00007ffff4a8d563 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#4  0x00007ffff4a8d9e8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#5  0x00007ffff4a61355 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#6  0x00007ffff4a165f4 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#7  0x00007ffff4a173cb in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#8  0x00007ffff4a1b816 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#9  0x00007ffff49b9a92 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#10 0x00007ffff49b374f in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#11 0x00007ffff49b3bf1 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#12 0x00007ffff49b4053 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#13 0x00007ffff472ebab in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#14 0x00007ffff466aa6d in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#15 0x00007ffff466ab1d in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#16 0x00007ffff45d5d10 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#17 0x00007ffff45d53b0 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#18 0x00007ffff4675115 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#19 0x00005555555f1868 in voxelFrame_c::drawVoxelSpace (this=0x5555557a5230) at gui/voxelframe.cpp:682
#20 0x00005555555f4313 in voxelFrame_c::draw (this=0x5555557a5230) at gui/voxelframe.cpp:1568
#21 0x00005555555f5ae1 in voxelFrame_c::pickShape (this=0x5555557a5230, x=732, y=597, shape=shape@entry=0x7fffffffd238, voxel=voxel@entry=0x0, face=face@entry=0x0) at gui/voxelframe.cpp:1632
#22 0x00005555555c27a5 in mainWindow_c::cb_3dClick (this=0x5555557a40a0) at /usr/include/FL/Fl.H:598
#23 0x00007ffff7edcc21 in Fl_Widget::do_callback (this=0x5555557a5140, o=0x5555557a5140, arg=0x5555557a40a0) at ./src/Fl_Widget.cxx:348
#24 0x00007ffff7edcc21 in Fl_Widget::do_callback (this=this@entry=0x5555557a5230, o=o@entry=0x5555557a5230, arg=0x5555557a5140) at ./src/Fl_Widget.cxx:348
#25 0x00005555555f0a20 in Fl_Widget::do_callback (this=0x5555557a5230) at /usr/include/FL/Fl_Widget.H:861
#26 voxelFrame_c::handle (event=1, this=0x5555557a5230) at gui/voxelframe.cpp:1600
#27 voxelFrame_c::handle (this=0x5555557a5230, event=1) at gui/voxelframe.cpp:1580
#28 0x00007ffff7e9a51e in send (event=1, o=0x5555557a5230) at ./src/Fl_Group.cxx:108
#29 send (o=0x5555557a5230, event=1) at ./src/Fl_Group.cxx:97
#30 0x00007ffff7e9ad3c in Fl_Group::handle (this=<optimized out>, event=1) at ./src/Fl_Group.cxx:228
#31 0x00005555555f087e in LView3dGroup::handle (this=0x5555557a5140, event=1) at gui/view3dgroup.cpp:72
#32 0x00007ffff7e9ad3c in Fl_Group::handle (this=<optimized out>, event=1) at ./src/Fl_Group.cxx:228
#33 0x00007ffff7e9ad3c in Fl_Group::handle (this=<optimized out>, event=1) at ./src/Fl_Group.cxx:228
#34 0x00007ffff7e9ad3c in Fl_Group::handle (this=<optimized out>, event=1) at ./src/Fl_Group.cxx:228
#35 0x00007ffff7e9ad3c in Fl_Group::handle (this=<optimized out>, event=1) at ./src/Fl_Group.cxx:228
#36 0x00007ffff7e84422 in Fl_Window::handle (this=<optimized out>, ev=<optimized out>) at ./src/Fl.cxx:1731
#37 0x00005555555bfebe in mainWindow_c::handle (this=0x5555557a40a0, event=1) at gui/mainwindow.cpp:2973
#38 0x00007ffff7e82993 in send_event (event=event@entry=1, to=to@entry=0x5555557a40a0, window=window@entry=0x5555557a40a0) at ./src/Fl.cxx:1220
#39 0x00007ffff7e84675 in Fl::handle_ (window=0x5555557a40a0, e=1) at ./src/Fl.cxx:1349
#40 Fl::handle_ (e=1, window=0x5555557a40a0) at ./src/Fl.cxx:1318
#41 0x00007ffff7ee419a in fl_handle (thisevent=...) at ./src/Fl_x.cxx:2258
#42 0x00007ffff7ee58a2 in do_queued_events () at ./src/Fl_x.cxx:212
#43 0x00007ffff7ee5c02 in fl_wait (time_to_wait=time_to_wait@entry=0.5) at ./src/Fl_x.cxx:278
#44 0x00007ffff7e84139 in Fl::wait (time_to_wait=time_to_wait@entry=0.5) at ./src/Fl.cxx:627
#45 0x00005555555a6989 in my_Fl::run (ui=<optimized out>) at gui/main.cpp:51
#46 main (argc=1, argv=0x7fffffffdf88) at gui/main.cpp:81
```

**Comment by raoulb** [comment]
Hmm, I really wish I could fix this! But no progress made so far :-/

**Comment by raoulb** [comment]
Ok, gave it another try and found at least a workaround, see PR #24

**Comment by raoulb** [comment]
Current backtrace (prior to the workaround commit):
```
Thread 1 "burrGui" received signal SIGSEGV, Segmentation fault.
0x00007fffecfdbdc2 in ?? () from /lib/x86_64-linux-gnu/libLLVM-18.so.18.1
(gdb) bt
#0  0x00007fffecfdbdc2 in ?? () from /lib/x86_64-linux-gnu/libLLVM-18.so.18.1
#1  0x00007fffed034149 in LLVMBuildBitCast () from /lib/x86_64-linux-gnu/libLLVM-18.so.18.1
#2  0x00007ffff478a992 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#3  0x00007ffff478e60b in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#4  0x00007ffff478ea7b in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#5  0x00007ffff475f3e1 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#6  0x00007ffff4710cb7 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#7  0x00007ffff471168b in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#8  0x00007ffff47151d0 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#9  0x00007ffff46a4dcb in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#10 0x00007ffff469d969 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#11 0x00007ffff469dded in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#12 0x00007ffff469e28d in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#13 0x00007ffff442da6d in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#14 0x00007ffff442def7 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#15 0x00007ffff4206614 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#16 0x00007ffff4204f38 in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#17 0x00007ffff433d01d in ?? () from /lib/x86_64-linux-gnu/libgallium-24.2.2-1.so
#18 0x00005555555d2eb5 in voxelFrame_c::drawVoxelSpace (this=<optimized out>) at gui/voxelframe.cpp:682
#19 0x00005555555d53a2 in voxelFrame_c::draw (this=0x5555557be780) at gui/voxelframe.cpp:1568
#20 0x00005555555d6dee in voxelFrame_c::pickShape (this=0x5555557be780, x=295, y=799, shape=shape@entry=0x7fffffffcd68, voxel=voxel@entry=0x0, face=face@entry=0x0) at gui/voxelframe.cpp:1632
#21 0x00005555555a5e55 in mainWindow_c::cb_3dClick (this=0x5555557a3950) at gui/mainwindow.cpp:1331
#22 0x00007ffff7eca585 in Fl_Widget::do_callback(Fl_Widget*, void*) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#23 0x000055555558cc7b in Fl_Widget::do_callback() ()
#24 0x00005555555d1b2d in cb_View3dGroupVoxel_stub(Fl_Widget*, void*) ()
#25 0x00007ffff7eca585 in Fl_Widget::do_callback(Fl_Widget*, void*) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#26 0x00005555555d2064 in Fl_Widget::do_callback (this=0x5555557be780) at /usr/include/FL/Fl_Widget.H:861
#27 voxelFrame_c::handle (this=0x5555557be780, event=1) at gui/voxelframe.cpp:1591
#28 0x00007ffff7e874c9 in ?? () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#29 0x00007ffff7e87c9b in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#30 0x00005555555d1e5d in LView3dGroup::handle(int) ()
#31 0x00007ffff7e87c9b in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#32 0x00007ffff7e87c9b in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#33 0x00005555555e3927 in LFl_Tile::handle(int) ()
#34 0x00007ffff7e87c9b in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#35 0x00007ffff7e87c9b in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#36 0x00005555555a366e in mainWindow_c::handle (this=0x5555557a3950, event=1) at gui/mainwindow.cpp:2961
#37 0x00007ffff7e6f233 in ?? () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#38 0x00007ffff7e71095 in Fl::handle_(int, Fl_Window*) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#39 0x00007ffff7ed1dd2 in fl_handle(_XEvent const&) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#40 0x00007ffff7ed3442 in ?? () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#41 0x00007ffff7ed37aa in fl_wait(double) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#42 0x00007ffff7e70b66 in Fl::wait(double) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
#43 0x00005555555a3474 in my_Fl::run(mainWindow_c*) ()
#44 0x00005555555a3126 in main ()
```
